### ISSUE TITLE
Explanation on December 4 problem

### ISSUE THREAD

**Issue by ASHIK11ab** [SVCE-ACM/A-December-of-Algorithms-2021#19]
Can you provide with some example for explanation of December 4 problem.

**Comment by nityasam02** [comment]
Yes, have made changes, pls do check it out in the DOA page.

**Comment by NikhileshJr08** [comment]
Hey @ASHIK11ab. We'll give more sample inputs/outputs and explanation for the 4th question. Meanwhile, keep trying out the other problems.
