### ISSUE TITLE
Input Format

### ISSUE THREAD

**Issue by hridyanshuk** [SVCE-ACM/A-December-of-Algorithms-2021#29]
Hi,
    For those using C++, C or Java, what is the input format.
    Number of test cases, size of array. Also the constraints on the sizes of arrays, and number of testcases are not given.
Eg.
```
2 // Number of test cases
3 // Number of necklaces
"abcdde" "baccd" "eeabg" // Necklace list
4
"abc" "def" "ghi" "jkl"
```

**Comment by NikhileshJr08** [comment]
Hi @hridyanshuk 
The input format would be the format that we've given in the sample input and output. So please follow the same. 
When it comes to constraints, you need not worry too much about it. We won't be exceeding a certain threshold. 
I hope my answer is adequate. 

Thank you for showing interest in participating. We're looking forward to seeing your submission.
