### ISSUE TITLE
Explanation for Problem #04

### ISSUE THREAD

**Issue by DSAghicha** [SVCE-ACM/A-December-of-Algorithms-2021#33]
I am stuck with Problem 04, as I am unable to understand what is going on it. Can someone explain how second input (```10 10```) reached output ```508361223```?

**Comment by NikhileshJr08** [comment]
Hey @DSAghicha 
We'll address your query shortly. Until then you can move forward with the other questions as you will have to submit it by January 10th.

**Comment by darshaandaghicha** [comment]
@NikhileshJr08  Any Update on Explanation?
