### ISSUE TITLE
Error in Test Case II: Problem #13

### ISSUE THREAD

**Issue by darshaandaghicha** [SVCE-ACM/A-December-of-Algorithms-2021#37]
In [Problem 13](https://github.com/DSAghicha/A-December-of-Algorithms-2021#december-13---desert-shopping) Test Case II, I believe output should be 0.

**Explanation:**

For Client 0: 
- Diamond 0 has purity greater than required but is out of budget.
- Diamond 1 has purity lesser than required.
So, Client 0 purchases neither.

For Client 1:
 - Neither diamonds have purity greater than required. 
 So, Client 1 purchases neither.

**Hence, sales should be 0**

**Comment by ASHIK11ab** [comment]
Yes @DSAghicha is right.
