### ISSUE TITLE
Dec:4 -Industry 

### ISSUE THREAD

**Issue by calledforth** [SVCE-ACM/A-December-of-Algorithms-2021#46]
Alright so I'm supposed to check which subsets of original set has maximum profit by adding up the  values  for each subset... But for the first input the maximum profit turns out to be 24 ->{5,4,7,8} and not 23->{5,4,-1,7,8} .. so is this just a mistake or am I misunderstanding smth?

**Comment by neha2127** [comment]
Hi
So sorry for the late reply. Please ensure you raise a query in the correct repository i.e (2022) as the current repository is not valid.

Regarding your question:

The values you take must be continuous and hence in the above case, when we add -1 to 24 it becomes 23. The solution specifies the starting index and the ending alone and so you cannot ignore ANY value between them. 

I hope this helps.

If there is further doubt, please raise a new issue in the "A December of Algorithms 2022" repository.

Good luck!
